### ISSUE TITLE
Investigate why the color generated with NVENC has artifacts

### ISSUE THREAD

**Issue by ehfd** [selkies-project/selkies-gstreamer#12]
noVNC:
![image](https://user-images.githubusercontent.com/8457324/152370803-d9303601-faae-487c-bab5-6235d63ecd28.png)
selkies-gstreamer x264enc:
![image](https://user-images.githubusercontent.com/8457324/152369879-c2bcb666-bcb2-496d-a979-9b3e427b9622.png)
selkies-gstreamer nvh264enc:
![image](https://user-images.githubusercontent.com/8457324/152370329-f5694832-5cf7-4988-99cf-7636589b888c.png)

Screenshot with 12 mbps video, 60 fps, 64 kbps audio.

When observed very carefully, the color in "Software Updater" seems a bit blurred for nvh264enc. The eye becomes a bit tired like looking at stereoscopic display. This artifact persists through various media across the screen. While not critical, finding why this happens can be helpful for quality control.

Will need to investigate the NVENC API linked with selkies-gstreamer.

**Comment by xhejtman** [comment]
As of colors, are you using subpixel antialiasing on remote? This is common result of (mostly wrong) setting of subpixel antialiasing that is using R, G, B pixels to do more font antialiasing, try to turn off or set grayscale only. 

I think it is visible with NVENC only as NVENC produces better image quality compared to CPU encoders, or perhaps subpixel antialiasing is turned off in the other cases?

**Comment by ehfd** [comment]
Is this something to do with Xorg configuration in the containers, or the encoding module?

**Comment by xhejtman** [comment]
No, it is not Xorg thing, but desktop settings like this:

![fonts](https://user-images.githubusercontent.com/22795052/163941148-bdd0d0b7-1a73-423a-b937-3494526cb9cc.png)

this is from Xfce. And subpixel should be set to none. Gnome should have similar settings somewhere.

**Comment by ehfd** [comment]
![image](https://user-images.githubusercontent.com/8457324/166109693-2cfa05a3-61b9-472c-96cd-c13a113c16e0.png)
I tried tweaking things here, and I don't think I get a fundamental change.
![image](https://user-images.githubusercontent.com/8457324/166109742-bc509683-8242-4a4c-957b-16d7a0b2d620.png)
I turned everything off but the color is still a bit off in white text.

**Comment by xhejtman** [comment]
could you try it using `xmag` to se whether font is ok? It is possible that some texts need desktop restart after changing font rendering.

**Comment by ehfd** [comment]
This is not that concerning as of now. Artifacts have been mostly okay and undetectable. Closing.

**Comment by ehfd** [comment]
Works rather well nowadays.
