### ISSUE TITLE
Pass remote cursor to client

### ISSUE THREAD

**Issue by danisla** [selkies-project/selkies-gstreamer#14]
Use XFixes extension to listen to mouse cursor change events and send the updated cursor to the browser over the Data Channel to be rendered locally.

Currently using [python-xlib](https://github.com/python-xlib/python-xlib/blob/master/Xlib/ext/xfixes.py) which doesn't appear to support XFixesCursorNotifyEvent.

Another [example](https://stackoverflow.com/questions/64539598/how-to-track-cursor-images-in-python-under-linux) showing how to use the C Libs directly.

## Work left to go
- [x] Capture XFixesCursorNotify event with python-xlib library.
- [x] Convert cursor image to PNG.
- [x] Send cursor image over Data Channel
- [x] Decode and render cursor with CSS.

**Comment by danisla** [comment]
[This branch](https://github.com/selkies-project/python-xlib/tree/add-xfixes-cursor) adds support for the `XFixesCursorNotifyEvent` and the `GetCursorImage` request.

## Work left to go before merging upstream:
- [ ] write example script showing usage in `examples/xfixes-cursor-notify.py`

**Comment by danisla** [comment]
Making some progress on this branch:

https://github.com/selkies-project/selkies-gstreamer/tree/remote-cursors

However, the cursors appear ghostly at the moment. Probably something with the PNG conversion.

![ghost cursor](https://user-images.githubusercontent.com/323725/152629275-94bfbf02-8762-43b0-8e37-3b27fe932542.jpg)

**Comment by danisla** [comment]
Fixed cursor transparency issue. The PNG library was expecting pixels in R,G,B,A order and I was decoded them in A,R,G,B per the XFixes spec.

There is still an offset issue, it looks like for some cursors the pixels wrap around. This is visible in the converted PNG data, so it is not a CSS or decoding issue.
![wrapping cursor pixels](https://user-images.githubusercontent.com/323725/152657719-0c4b8bc7-1bba-4d38-92a3-859cbd6a97f0.jpg)

**Comment by danisla** [comment]
Testing with XFCE4 and the `adwaita-icon-theme-full` package, the cursors appear huge. They are 96x96 pixels rather than 24x24.

![xfce large cursor](https://user-images.githubusercontent.com/323725/152659805-65ca71ae-e1e8-4b18-afb2-f8a6f3410c4c.jpg)

Probably need to resize the cursor image locally using [canvas image transformations](https://stackoverflow.com/questions/19262141/resize-image-with-javascript-canvas-smoothly). This will also help when supporting HiDPI.

**Comment by danisla** [comment]
Latest commit creates the cursor and resizes it using PIL. 
Seems to be working pretty well so far. Probably well enough for an initial release.

![scaled cursor](https://user-images.githubusercontent.com/323725/152882449-a8c1bc8d-426f-4950-9bbb-2299a96b26cd.jpg)

Remote cursors can be disabled by setting the env var `WEBRTC_ENABLE_CURSORS=false`

**Comment by JanCVanB** [comment]
Hehe, that ghostly cursor looks sparkly

**Comment by xhejtman** [comment]
I am getting https://github.com/selkies-project/selkies-gstreamer/issues/14#issuecomment-1030693327 issue as well with remote ubuntu focal and hirsute. It is ok on remote ubuntu 18. Any idea how to fix it?

**Comment by danisla** [comment]
@xhejtman this feature is complete on master and I am not able to reproduce it on my end.

Are you seeing this in the docker example that is based on focal?

```
docker-compose build
docker-compose run --service-ports test
```

**Comment by xhejtman** [comment]
I can confirm it is fixed if you install `adwaita-icon-theme-full` package.

**Comment by danisla** [comment]
I am actually able to reproduce it now with just the X server running and the default X11 cursors.
![cursor-issue-x11](https://user-images.githubusercontent.com/323725/164323314-78d4a30d-f2fb-4474-a937-abe4509d8ca0.jpg)

**Comment by xhejtman** [comment]
I suppose this is happening because for 2 color cursors it is broken? `adwaita-icon-theme-full` perhaps provides full RGB cursors.

**Comment by ehfd** [comment]
Almost done. Relevant code: https://github.com/selkies-project/selkies-gstreamer/blob/master/src/selkies_gstreamer/webrtc_input.py

**Comment by ehfd** [comment]
This can be closed if there is a new PyPi release of [python-xlib](https://github.com/python-xlib/python-xlib/blob/master/Xlib/ext/xfixes.py).

**Comment by ehfd** [comment]
New release is out. Version 0.32.

**Comment by MWsDev79** [comment]
Will this work for Cloud Gaming as well? I'm using linux to game on GeForce Now cloud server. I'm looking for a linux version of CursorNode which is an app that allow you to force your custom cursor in any app, including remote servers. It works well. I need something similar on Linux because of vision impairment in one eye and the need for a larger cursor using this remote server.

**Comment by ehfd** [comment]
> Will this work for Cloud Gaming as well?

@MWsDev79 We are intended for cloud gaming. And it works now. And I believe that if you find an equivalent of CursorNode and install it in your node or container, Selkies will pass it to the web interface.

**Comment by ehfd** [comment]
@MWsDev79 Please feel free to contact us on Discord (https://discord.gg/wDNGDeSW5F) if you need more assistance.

**Comment by ehfd** [comment]
@MWsDev79 
https://github.com/selkies-project/selkies-gstreamer/blob/ee2a27db9cf602c077479a8099ad3d653454a1c3/src/selkies_gstreamer/webrtc_input.py#L114
This defines our local cursor size, it would be trivial to change this dynamically.
Remote cursor is set by the desktop environment.
I will take a look at this when I remember to do it.

**Comment by ehfd** [comment]
@MWsDev79 I have added the capability to scale the size of our local cursor (will be in the next release, use `WEBRTC_CURSOR_SIZE` in points), but the remote cursor must be configured within the OS.

**Comment by MWsDev79** [comment]
That looks perfect!!!! 
And will solve my issue. 
TY

**Comment by ehfd** [comment]
@MWsDev79 

Note:

```Mouse pointer is too small and does not follow system size in Qt/KDE applications: This is a new bug in Qt 5.15.1. Qt and KDE programs get a tiny mouse cursor while all other programs will follow the system-wise mouse pointer size. A work-around for this is to export XCURSOR_SIZE=48 or start Qt and KDE programs with XCURSOR_SIZE=48 programname. Setting the mouse cursor size in systemsettings5 will only make it big in that particular program and only until you close it; re-opening it or opening any other Qt or KDE program results in a tiny mouse cursor if you have Qt 5.15.1 and you haven't explicitly set XCURSOR_SIZE=```

https://linuxreviews.org/KDE_Plasma

Affected in Ubuntu 22.04.

I added a way to prioritize XCURSOR_SIZE over the command line argument, should be in the next minor release.
