### ISSUE TITLE
Knowledge exchange?

### ISSUE THREAD

**Issue by JanCVanB** [selkies-project/selkies-gstreamer#29]
@xhejtman Thank you for sharing your improvements in #7! Are you interested in meeting with @danisla and me over audio/video in [the Selkies Discord server](https://discord.gg/TjZ2tBhq) sometime? We'd like to learn more about your use case and exchange knowledge about gstreamer (and any other shared dependencies). Your teammates are also welcome! 🙂

**Comment by xhejtman** [comment]
Yes, no problem ;)

**Comment by JanCVanB** [comment]
Great! Direct message me on Discord, and we'll schedule a time.
