### ISSUE TITLE
dns

### ISSUE THREAD

**Issue by kfox1111** [selkies-project/selkies-gstreamer#38]
Just tried the example from the webpage on a centos8 stream system s/docker/podman/. While connecting with a browser, it just sits there "Waiting for video stream" and the following is printed in the logs:
0:04:47.907950623    47      0x3088f00 ERROR              webrtcice gstwebrtcice.c:289:_resolve_host: Error resolving “7125f11a-e853-4553-b81c-ecf214892303.local”: Name or service not known

**Comment by ehfd** [comment]
You need a TURN Server, did you set a TURN server address to something that you have set up?

> 0:04:47.907950623 47 0x3088f00 ERROR webrtcice gstwebrtcice.c:289:_resolve_host: Error resolving “7125f11a-e853-4553-b81c-ecf214892303.local”: Name or service not known
This is not an issue, this is an error that has no effect.

**Comment by kfox1111** [comment]
That worked. Thanks.

**Comment by mixxen** [comment]
@kfox1111, I'm seeing the same issue running in a podman container. Can you share how you set up the TURN server? Thanks.

**Comment by ehfd** [comment]
@mixxen Check https://github.com/selkies-project/selkies-gstreamer/tree/master/addons/coturn
Configuration at https://github.com/coturn/coturn/blob/master/examples/etc/turnserver.conf

**Comment by ehfd** [comment]
Container: https://hub.docker.com/r/coturn/coturn

```docker run -d -p 3478:3478 -p 3478:3478/udp -p 49160-49200:49160-49200/udp coturn/coturn -n  --min-port=49160 --max-port=49200```
