### ISSUE TITLE
Struggling to get demo container functioning

### ISSUE THREAD

**Issue by rhastie** [selkies-project/selkies-gstreamer#5]
Sorry for the complete newbie question but I'm really struggling to get the demonstration container to run...

I have a Ubuntu 20.04 env with latest docker installed... I am running Ubuntu with no X11 operating on the host - so hopefully no port conflicts etc.

When I run the docker run command I just get a repeating error:

screen 0 shmid 0
/entrypoint.sh: 2: [[: not found
error repeats....

I have also tried running the container with --user root but again to no avail...

I'm guessing I'm being a complete idiot but any pointers would be gratefully appreciated... Thanks

**Comment by rhastie** [comment]
Small step forward in terms of running this container...

You need to add "#!/bin/bash" to the beginning of your entrypoint.sh script... This is causing the error and issue

Without that shebang line, your script will be interpreted by `sh` which doesn't understand `[[` in the `until` statement.

Still having issues connecting to the WebRTC stream but currently trying to debug that - Just getting "Connection error, retry in 3 seconds." Any thoughts or ideas?

**Comment by danisla** [comment]
Thanks for the heads up on this. It should be fixed with [this commit](https://github.com/selkies-project/selkies-gstreamer/commit/9ec2250b8373714bc68da1bf78476db981ee62c0).

The connection error is an issue with forcing `wss://` rather than detecting the protocol in JS. The fix for that is also on master now.

**Comment by danisla** [comment]
I'm gonna close this now, please re-open if you are still having trouble.
