### ISSUE TITLE
Multiple-monitor remote desktop

### ISSUE THREAD

**Issue by backcountrymountains** [selkies-project/selkies-gstreamer#52]
There doesn't seem to be a github discussion area for this project so I'm putting this here.

I'm trying to find the perfect multiple-monitor, low-latency, high-resolution, hardware-accelerated remote desktop solution. I just want to have a thin client with two 4k monitors remotely stream my home computer that has two 4k monitors and a 1660ti.

I'm not any kind of coder or technologist but it seems like all of the components exist for this to work.

Can this project stream my multiple-monitor extended desktop to a thin client with two monitors?

Thanks!

Also, is there a website or anything with tutorials and stuff for this?

**Comment by ehfd** [comment]
Hi!
I just wrote documentation that will soon be merged to master. You can see right now in #51.
I have had the same question as you a year ago before I teamed up with Selkies. I have no suspicion that this project is for you.

**Comment by ehfd** [comment]
@danisla I think we should merge #51 soon

**Comment by ehfd** [comment]
https://github.com/selkies-project/selkies-gstreamer/blob/documentation/README.md

**Comment by ehfd** [comment]
The tutorial was merged to master. Just use different `DISPLAY` environment variables to two different shell processes, then start two different selkies-gstreamer processes with different listening ports. Tell me if it works.

**Comment by ehfd** [comment]
Although Discussions are now available, I think this should still remain in the issues.

**Comment by ehfd** [comment]
Documentation added. Closing. Please revive this issue when there is another related question.

**Comment by joshzhaa** [comment]
I'm trying to run multiple instances of selkies-gstreamer, one with DISPLAY=:0 and another with DISPLAY=:1, but no matter what arguments I use for the --port and --addr options, the second instance of selkies-gstreamer always errors out with "[Errno 98] error while attempting to bind on address ('0.0.0.0', 8081): address already in use" What is the correct way to run multiple instances of selkies-gstreamer?

**Comment by ehfd** [comment]
I believe that this is because of `--metrics_port`. Try setting this to different ports.

@joshzhaa Please tell me if this works.

**Comment by joshzhaa** [comment]
Making sure the metrics_port doesn't conflict solved the problem. Thanks for the suggestion.

**Comment by ehfd** [comment]
@joshzhaa using lsof is the natural next step
